layoutBootstrap:
  enabled: true
  zone: dc1
  capacity: 1G
  image:
    repository: alpine/k8s
    tag: "1.35.6"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

bucketBootstrap:
  enabled: true
  suspend: true
  schedule: "0 0 1 1 *"
  bucket: default-bucket
  keyName: default-app-key
  secretName: myapp-s3-credentials
  image:
    repository: alpine/k8s
    tag: "1.35.6"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

garage:
  initResources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  garage:
    rbac:
      clusterScoped: false
    # Use only 2 replicas per object
    replicationFactor: 1
    kubernetesSkipCrd: true
  # Start 4 instances (StatefulSets) of garage
  deployment:
    replicaCount: 1

  # Override default storage class and size
  persistence:
    meta:
#      storageClass: "openebs-hostpath"
      size: 1Gi
    data:
#      storageClass: "openebs-hostpath"
      size: 1Gi

  ingress:
    s3:
      api:
        enabled: true
#        className: "public"
#        annotations:
#          cert-manager.io/cluster-issuer: "letsencrypt-prod"
#          nginx.ingress.kubernetes.io/proxy-body-size: 500m
        hosts:
          - host: s3customdomain.app.cpin.numerique-interieur.fr
            paths:
              - path: /
                pathType: Prefix
